kubelet:
    labels:
        io.rancher.container.dns: "true"
        io.rancher.container.create_agent: "true"
        io.rancher.container.agent.role: environment
        io.rancher.scheduler.global: "true"
    command:
        - kubelet
        - --api_servers=http://master
        - --allow-privileged=true
        - --register-node=true
        - --cloud-provider=rancher
        - --healthz-bind-address=0.0.0.0
        - --cluster-dns=169.254.169.250
        - --cluster-domain=cluster.local
    image: rancher/k8s:v1.2.0-rancher-1
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/run:/host/var/run
        - /var/lib/docker:/var/lib/docker
    net: host
    pid: host
    ipc: host
    privileged: true
    links:
        - kubernetes:master

proxy:
    labels:
        io.rancher.container.dns: "true"
        io.rancher.scheduler.global: "true"
    command:
        - kube-proxy
        - --master=http://master
        - --v=2
        - --healthz-bind-address=0.0.0.0
        - --proxy-mode=userspace
    image: rancher/k8s:v1.2.0-rancher-1
    privileged: true
    net: host
    links:
        - kubernetes:master

etcd:
    image: rancher/etcd:v2.3.3
    command: node 3
    labels:
        io.rancher.sidekicks: etcd-data
        io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    volumes_from:
        - etcd-data

etcd-data:
    image: busybox
    command: /bin/true
    net: none
    volumes:
        - /data
    labels:
        io.rancher.container.start_once: 'true'

etcd-discovery:
    image: rancher/etcd:v2.3.3
    command: discovery_node
    labels:
        io.rancher.container.start_once: 'true'
        io.rancher.sidekicks: etcd-bootstrap

etcd-bootstrap:
    image: rancher/etcd:v2.3.3
    command: bootstrap 3
    links:
        - etcd-discovery
    labels:
        io.rancher.container.start_once: 'true'

kubernetes:
    labels:
        io.rancher.container.create_agent: "true"
        io.rancher.container.agent.role: environment
    command: 
        - kube-apiserver
        - --service-cluster-ip-range=10.43.0.0/16
        - --etcd-servers=http://etcd:2379
        - --insecure-bind-address=0.0.0.0
        - --insecure-port=80
        - --cloud-provider=rancher
        - --allow_privileged=true
        - --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ResourceQuota
    image: rancher/k8s:v1.2.0-rancher-1
    links:
        - etcd

kubectld:
    labels:
        io.rancher.k8s.kubectld: "true"
    environment:
        SERVER: http://master
        LISTEN: ":8091"
    image: rancher/kubectld:v0.1.0
    links:
        - kubernetes:master

scheduler:
    command:
        - kube-scheduler
        - --master=http://master
        - --address=0.0.0.0
    image: rancher/k8s:v1.2.0-rancher-1
    links:
        - kubernetes:master

controller-manager:
    command:
        - kube-controller-manager
        - --master=http://master
        - --cloud-provider=rancher
        - --address=0.0.0.0
    image: rancher/k8s:v1.2.0-rancher-1
    labels:
        io.rancher.container.create_agent: "true"
        io.rancher.container.agent.role: environment
    links:
        - kubernetes:master

rancher-kubernetes-agent:
    labels:
        io.rancher.container.create_agent: "true"
        io.rancher.container.agent_service.labels_provider: "true"
    environment:
        KUBERNETES_URL: http://master
    image: rancher/kubernetes-agent:v0.1.0
    privileged: true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    links:
        - kubernetes:master
